version: "3.8"
services:
  kafka:
    image: apache/kafka:3.8.0
    restart: always
    ports:
      - "9092:9092"
  postgres:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "6432:5432"
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
